library(ggplot2)
library(dplyr)
PM25data <- readRDS("summarySCC_PM25.rds")
Baltimore_PM25data <- subset(PM25data, fips == "24510")
Baltimore_PM25data <- transform(Baltimore_PM25data, type = as.factor(type), year = as.factor(year))
Baltimore_PM25data_sum <- group_by(Baltimore_PM25data, type, year) %>% summarise(emission_sum = sum(Emissions))
ggplot(aes(x=year, y=emission_sum, color=type, group=type), data = Baltimore_PM25data_sum)+ geom_point()+geom_line(lwd = 1)+labs(x = "Year", y = expression("Total PM"[2.5] * " Emissions in Baltimore City by Type of Source"))
dev.copy(png, file = "plot3.png")
dev.off()
